/**
 * Flaneur OSM Recorder — Export Module
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Exports session nodes to OSM XML, GPX, or GeoJSON.
 * OSM XML is the primary format for JOSM import.
 *
 * JOSM import workflow:
 *   File › Open the .osm file → nodes appear as new layer
 *   Review, adjust, add detail → upload through JOSM normally
 *
 * Note on photos: photos are NOT embedded in exports.
 * They must be uploaded externally (Mapillary / Wikimedia Commons)
 * and the URL linked as a tag (e.g. image=https://...) in JOSM.
 */

// ─── OSM XML ──────────────────────────────────────────────────────────────

export function toOsmXml(session) {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Generated by Flaneur OSM Recorder — session: ${session.id} -->`,
    `<!-- Created: ${session.createdAt} | Nodes: ${session.nodes.length} -->`,
    '<!-- SPDX-License-Identifier: ODbL-1.0 (data) — upload via JOSM after review -->',
    '<osm version="0.6" generator="flaneur-osm-recorder">',
  ];

  for (const node of session.nodes) {
    const attrs = [
      `id="${node.id}"`,
      `lat="${node.lat.toFixed(7)}"`,
      `lon="${node.lon.toFixed(7)}"`,
      'action="create"',
      `timestamp="${node.timestamp}"`,
    ].join(' ');

    lines.push(`  <node ${attrs}>`);

    for (const [k, v] of Object.entries(node.tags)) {
      lines.push(`    <tag k="${escXml(k)}" v="${escXml(v)}"/>`);
    }

    if (node.note) {
      lines.push(`    <tag k="note" v="${escXml(node.note)}"/>`);
    }

    if (node.accuracy_m != null) {
      lines.push(`    <tag k="flaneur:accuracy" v="${node.accuracy_m.toFixed(1)}m"/>`);
    }

    lines.push('  </node>');
  }

  lines.push('</osm>');
  return lines.join('\n');
}

// ─── GPX ──────────────────────────────────────────────────────────────────

export function toGpx(session) {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<gpx version="1.1" creator="flaneur-osm-recorder"',
    '  xmlns="http://www.topografix.com/GPX/1/1"',
    '  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">',
    `  <metadata><name>${escXml(session.name)}</name><time>${session.createdAt}</time></metadata>`,
  ];

  for (const node of session.nodes) {
    const tagStr = Object.entries(node.tags)
      .map(([k, v]) => `${k}=${v}`)
      .join('; ');

    lines.push(`  <wpt lat="${node.lat.toFixed(7)}" lon="${node.lon.toFixed(7)}">`);
    lines.push(`    <time>${node.timestamp}</time>`);
    lines.push(`    <name>${escXml(tagStr.split(';')[0])}</name>`);

    const desc = [tagStr, node.note ? `note: ${node.note}` : '']
      .filter(Boolean)
      .join(' | ');
    lines.push(`    <cmt>${escXml(desc)}</cmt>`);
    lines.push(`    <desc>${escXml(desc)}</desc>`);
    lines.push('  </wpt>');
  }

  lines.push('</gpx>');
  return lines.join('\n');
}

// ─── GeoJSON ──────────────────────────────────────────────────────────────

export function toGeoJson(session) {
  const features = session.nodes.map((node) => ({
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [
        parseFloat(node.lon.toFixed(7)),
        parseFloat(node.lat.toFixed(7)),
      ],
    },
    properties: {
      ...node.tags,
      note: node.note || '',
      timestamp: node.timestamp,
      accuracy_m: node.accuracy_m,
      flaneur_id: node.id,
    },
  }));

  return JSON.stringify(
    {
      type: 'FeatureCollection',
      name: session.name,
      generated_by: 'flaneur-osm-recorder',
      session_id: session.id,
      features,
    },
    null,
    2
  );
}

// ─── Download helper ──────────────────────────────────────────────────────

export function downloadText(content, filename, mimeType) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }, 1000);
}

export function exportSession(session, format) {
  const datePart = session.createdAt.slice(0, 10).replace(/-/g, '');
  const base = `flaneur_${datePart}`;

  if (format === 'osm') {
    downloadText(toOsmXml(session), `${base}.osm`, 'application/xml');
  } else if (format === 'gpx') {
    downloadText(toGpx(session), `${base}.gpx`, 'application/gpx+xml');
  } else if (format === 'geojson') {
    downloadText(toGeoJson(session), `${base}.geojson`, 'application/geo+json');
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────

function escXml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
