#!/usr/bin/env node
/**
 * Flaneur OSM Recorder — icon attribution generator
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 *   node tools/build-credits.mjs           # rewrite the block in README.md
 *   node tools/build-credits.mjs --check   # fail if README.md is out of date
 *
 * Rewrites everything between the ICON-CREDITS markers in README.md from
 * src/icons/icon-sources.json and src/js/presets.js, so attribution cannot
 * drift away from what is actually shipped.
 *
 * This is not housekeeping. Material Design Icons is Apache-2.0, which
 * REQUIRES the attribution notice be retained in distributions — an MDI icon
 * shipped without a credit line is a licence violation. The CC0 sets impose no
 * such obligation; they are credited because taking public-domain work without
 * saying where it came from is poor practice, not because a licence compels it.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { allPresets, FALLBACK_ICON } from '../src/js/presets.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const README = join(ROOT, 'README.md');
const MANIFEST = join(ROOT, 'src', 'icons', 'icon-sources.json');

const START =
  '<!-- ICON-CREDITS:START — generated by tools/build-credits.mjs, do not edit by hand -->';
const END = '<!-- ICON-CREDITS:END -->';

const check = process.argv.includes('--check');

const manifest = JSON.parse(await readFile(MANIFEST, 'utf8'));

/** ref → the preset ids that use it, so a reader can trace any icon back. */
const usage = new Map();
for (const preset of allPresets()) {
  if (!usage.has(preset.iconRef)) usage.set(preset.iconRef, []);
  usage.get(preset.iconRef).push(preset.id);
}
if (!usage.has(FALLBACK_ICON)) usage.set(FALLBACK_ICON, ['(fallback for unmatched nodes)']);

/** set → refs, in manifest order. */
const bySet = new Map();
for (const ref of manifest.icons) {
  const setId = ref.split(':')[0];
  if (!bySet.has(setId)) bySet.set(setId, []);
  bySet.get(setId).push(ref);
}

const lines = [];
lines.push(START);
lines.push('');
lines.push(
  'The preset buttons use freely-licensed SVG icons, vendored into `src/icons/`.',
  'Every set below is compatible with GPL-3.0-or-later. Provenance for each',
  'individual icon is in [`src/icons/icon-sources.json`](./src/icons/icon-sources.json);',
  '`npm test` fails if an icon ships without an entry there.',
  ''
);

for (const [setId, refs] of bySet) {
  const set = manifest.sets[setId];
  const shipped = refs.filter((r) => usage.has(r));

  lines.push(`### ${set.name}`);
  lines.push('');
  lines.push(`- **Licence:** ${set.license} — <${set.licenseUrl}>`);
  lines.push(
    `- **Source:** ${set.homepage.startsWith('http') ? `<${set.homepage}>` : `\`${set.homepage}\``}`
  );
  lines.push(`- **Shipped here:** ${shipped.length} icon${shipped.length === 1 ? '' : 's'}`);
  if (set.license === 'Apache-2.0') {
    lines.push(
      '- Apache-2.0 requires this notice be retained in distributions. **Do not delete this section.**'
    );
  } else if (set.license === 'CC0-1.0') {
    lines.push('- Public domain dedication — attribution is courtesy here, not obligation.');
  }
  lines.push('');

  lines.push('<details><summary>Per-icon attribution</summary>');
  lines.push('');
  for (const ref of refs) {
    const id = ref.split(':')[1];
    const url = set.blob ? set.blob.replace('{id}', id) : `${set.homepage}${id}.svg`;
    const used = usage.get(ref);
    const link = url.startsWith('http') ? `<${url}>` : `\`${url}\``;
    lines.push(`- \`${ref}\` — ${link}${used ? ` — used by: ${used.join(', ')}` : ''}`);
  }
  lines.push('');
  lines.push('</details>');
  lines.push('');
}

lines.push('### Sets evaluated and rejected');
lines.push('');
lines.push(
  '- **osm-icons.org** — mostly CC0 (SJJB-derived), **but** the site publishes a',
  '  per-icon licence table and some entries are CC BY-SA 2.0. Never bulk-import.',
  '- **freesvg.org** — the ToS declares uploads CC0, but provenance is not verified',
  '  and the site disclaims liability. Clipart-detailed, not icon-grade at 24px.',
  '- **The Noun Project** — CC BY 3.0 with per-icon attribution in a prescribed',
  '  format, or paid. Usable, but it would pollute an otherwise clean pipeline.',
  '- **JOSM preset images** — GPL-2.0-or-later, so perfectly usable, and they have',
  '  the closest semantic match for a handful of presets (street cabinet, ticket',
  '  machine, substation, AED, cycle lane, kerb pattern). Not shipped because they',
  '  are **full colour** and would clash with a flat single-colour UI. Adopt them',
  '  only if you accept the colour or flatten them first.',
  ''
);
lines.push(END);

const block = lines.join('\n');
const readme = await readFile(README, 'utf8');

const startAt = readme.indexOf(START);
const endAt = readme.indexOf(END);
if (startAt === -1 || endAt === -1) {
  process.stderr.write(`Could not find the ICON-CREDITS markers in README.md.\n`);
  process.exit(1);
}

const updated = readme.slice(0, startAt) + block + readme.slice(endAt + END.length);

if (check) {
  if (updated !== readme) {
    process.stderr.write('README.md icon credits are out of date — run: npm run icons:credits\n');
    process.exit(1);
  }
  process.stdout.write('README.md icon credits are up to date.\n');
} else {
  await writeFile(README, updated);
  process.stdout.write(`Wrote icon credits for ${manifest.icons.length} icons to README.md\n`);
}
